import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
